version: 1.0.{build}
image: Visual Studio 2017

build_script:
- ps: >- 
    (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install.ps1") | iex
- cmd: >-       
    SET PATH=C:\Ruby24\bin;%PATH%

    gem install github_changelog_generator --prerelease --force

    refreshenv

    dir C:\Ruby24\bin

    C:\Ruby24\bin\github_changelog_generator -v

- cmd: >-
    SET PATH

    github_changelog_generator -v

test: off
environment:
    GITHUB_REPO_TOKEN:
        secure: FSPXTPuTgFMaZA7DubJoX217SkWhFLN2BGqCCi4gBux967eFtwkhbrafm7ay8cP2
    NUGET_APIKEY:
        secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm
    