version: 1.0.{build}
image: Visual Studio 2017
install:
- set PATH=C:\Ruby24-x64\bin;%PATH%
build_script:
- ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install.ps1") | iex
- ps: cd .\build\
           
- cmd: refreshenv
- cmd: dotnet script build.csx
    

test: off
environment:
    GITHUB_REPO_TOKEN:
        secure: FSPXTPuTgFMaZA7DubJoX217SkWhFLN2BGqCCi4gBux967eFtwkhbrafm7ay8cP2
    NUGET_APIKEY:
        secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm
